### ISSUE TITLE
Pipeline available to read annotation file geojson

### ISSUE THREAD

**Issue by tkcaccia** [mritchielab/SpatialBench#1]
It is an interesting pipeline. It would be wonderful to have a complete pipeline to read Visium data and Qupath annotation files.
The use of internal example makes it difficult to apply the pipeline to external datasets. 
Is the pipeline works as well as with VisiumHD data?

**Comment by mei-du** [comment]
Hi there,

Thank you for your interest in our work. 

Currently we do not have a single complete pipeline. Our workflow has a few steps and all their scripts are in the `analysis` folder. We outline how to use them in the repo description. They have been provided as an example to use with the SpatialBench dataset, so please edit the file and sample names in line with your dataset.

You may read and pre-process individual Visium samples with [EDA_709_FFPE_CA.Rmd](https://github.com/mritchielab/SpatialBenchVisium/blob/main/analysis/EDA_709_FFPE_CA.Rmd) (or [EDA_713_FFPE_CA.Rmd](https://github.com/mritchielab/SpatialBenchVisium/blob/main/analysis/EDA_713_FFPE_CA.Rmd)). To process multiple samples at the same time, follow [FFPE_CA_multi-sample.Rmd](https://github.com/mritchielab/SpatialBenchVisium/blob/main/analysis/FFPE_CA_multi-sample.Rmd). 

Qupath geojson files can be read with [qupath_classification.R](https://github.com/mritchielab/SpatialBenchVisium/blob/main/analysis/qupath_classification.R). The geojson files used in this script have also been included as an example.

We have not yet tested this pipeline with Visium HD data.
